# ===================================
# JailPlus Configuration
# ===================================

# Locale
# Basically support 'ru', 'en'
locale: "en"

# Use prefix in plugin messages
use-prefix: true

# ===================================
# Prison settings
# ===================================

# Max jail time in seconds
# use 0 to disable limit
max-jail-time: 604800

# Time to check valid conclusions (in ticks, 20 ticks = 1 second)
check-interval: 600

# Automatically release when time expires
auto-release: true

# ===================================
# Notification settings
# ===================================

#Notify server about conclusion
broadcast-jail: true

# Notify server when released
broadcast-unjail: true

# Notify player of time every X minutes
# use 0 to disable
notify-interval: 30

#Notify administrators when concluding
notify-admins: true

# Rights to receive notifications
admin-notification-permission: "jailplus.admin.notify"

# ===================================
# Restrictions for prisoners
# ===================================

# Disable the use of commands
prevent-command-usage: true

# Authorized Commands for Prisoners
unblocked-commands:
  - "tell"
  - "say"
  - "msg"
  - "server"
  - "help"
  - "rules"

# Disable block breaking
prevent-block-break: true

# Disable installation of blocks
prevent-block-place: true

# Block PvP
prevent-pvp: true

# Prevent opening inventories
prevent-inventory: true

# Disable teleportation
prevent-teleport: true

# Prevent mobs/players from damaging prisoners
prevent-damage-to-prisoners: true

# ===================================
# Advanced Features
# ===================================

# Enable logging system
enable-logging: false

# Maximum number of logs
# use 0 to disable limit
max-log-entries: 100

# Enable player statistics
enable-statistics: true


scoreboard:
  # Enable scoreboard for prisoners
  enabled: true

  # scoreboard update cooldown (in ticks)
  update-interval: 60

  # Show who jail player
  show-jailed-by: false

  # Show extra info (jail percent etc.)
  show-extra-info: false

  # Auto hide on release
  auto-hide-on-release: true

  # Show scoreboard only in jail world
  only-in-jail-world: false


# ===================================
# Effects and sounds
# ===================================

# Turn on sound effects
enable-sounds: true

# Sound when concluding
jail-sound: "entity.iron_golem.attack"

# Sound when released
unjail-sound: "entity.player.levelup"

# Enable particle effects
enable-particles: true

# Particles around prisoners
# All particle types: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
prisoner-particle: "WAX_ON"

# ===================================
# Database (experimental)
# ===================================

# Database type (YAML/MYSQL)
database-type: "YAML"

# MySQL settings (if used)
mysql:
  host: "localhost"
  port: 3306
  database: "jailplus"
  username: "user"
  password: "password"
  table-prefix: "jp_"

# ===================================
# PlaceholderAPI
# ===================================

# Enable integration with PlaceholderAPI
enable-placeholderapi: true

# Cache placeholder results (improves performance)
cache-placeholders: true

# Placeholder caching time in milliseconds
placeholder-cache-time: 5000

# Debug mode
debug: false