name: JailPlus
version: '${version}'
main: org.misqzy.jailPlus.JailPlus
api-version: '1.21'
author: MISQZY
description: Jail plugin with PlaceholderAPI support and advanced features

depend: []
softdepend: [Vault, PlaceholderAPI]

commands:
  jail:
    description: Jail player command
    usage: /<command> <player> [jail] [time] [reason] | /<command> list | /<command> info [player]
    permission: jailplus.jail
    aliases: [j]

  unjail:
    description: Unjail player
    usage: /<command> <player>
    permission: jailplus.unjail
    aliases: [uj, free]

  jailadmin:
    description: Admin commands
    usage: /<command> <subcommand>
    permission: jailplus.admin
    aliases: [ja, jadmin]

permissions:
  jailplus.*:
    description: Access to all JailPlus commands
    children:
      jailplus.jail.*: true
      jailplus.unjail: true
      jailplus.admin.*: true
      jailplus.reload: true
      jailplus.bypass: true
      jailplus.notify: true
      jailplus.placeholders: true
      jailplus.scoreboard.*: true
    default: op

  jailplus.jail:
    description: Access to jail command
    default: true

  jailplus.jail.*:
    description: Access to all jail commands
    children:
      jailplus.jail: true
      jailplus.jail.player: true
      jailplus.jail.list: true
      jailplus.jail.info.*: true
    default: op

  jailplus.jail.player:
    description: Access to jail player
    default: op

  jailplus.jail.list:
    description: Access to jail list
    default: true

  jailplus.jail.info:
    description: Access to jail info command
    default: true

  jailplus.jail.info.*:
    description: Access to all jail info commands
    children:
      jailplus.jail.info: true
      jailplus.jail.info.own: true
      jailplus.jail.info.other: true
    default: op

  jailplus.jail.info.own:
    description: Access to display own jail time
    default: true

  jailplus.jail.info.other:
    description: Access to display other player jail time
    default: op

  jailplus.unjail:
    description: Access to unjail player
    default: op

  jailplus.admin:
    description: Access to admin command
    default: false

  jailplus.admin.*:
    description: Access to all admin functions
    children:
      jailplus.admin: true
      jailplus.admin.create: true
      jailplus.admin.delete: true
      jailplus.admin.info: true
      jailplus.admin.list: true
      jailplus.admin.time: true
      jailplus.admin.logs: true
      jailplus.admin.stats: true
      jailplus.admin.notify: true
      jailplus.admin.scoreboard: true
    default: op

  jailplus.admin.create:
    description: Access to create jail
    default: op

  jailplus.admin.delete:
    description: Access to delete jail
    default: op

  jailplus.admin.info:
    description: Access to info about jail
    default: op

  jailplus.admin.list:
    description: Access to jail list
    default: op

  jailplus.admin.time:
    description: Access to manage prisoner time command
    default: op

  jailplus.admin.logs:
    description: Access to view logs
    default: op

  jailplus.admin.stats:
    description: Access to view statistics
    default: op

  jailplus.admin.notify:
    description: Receive admin notifications about jails
    default: op

  jailplus.admin.scoreboard:
    description: Access to scoreboard management commands
    default: op

  jailplus.scoreboard.*:
    description: Access to all scoreboard features
    children:
      jailplus.scoreboard.view: true
      jailplus.scoreboard.bypass: true
    default: op

  jailplus.scoreboard.view:
    description: View jail scoreboard information
    default: true

  jailplus.scoreboard.bypass:
    description: Bypass scoreboard restrictions (admin override)
    default: op


  jailplus.bypass:
    description: Bypass all jail restrictions
    default: false

  jailplus.reload:
    description: Reload plugin
    default: op

  jailplus.placeholders:
    description: Access to view placeholder information
    default: true